name: Mi megatriler

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  taller:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar ultimos cambios
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Visualizar Cambios
        run: ls -l