name: Mi megatriler

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build-redency:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancelar penultimo build
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{github.token}}
  execution-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar ultimos cambios
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Instalar y configurar JDK11
        uses: actions/setup-java@v3.4.1
        with:
          java-version: "11"
          distribution: "temurin"
          server-id: github
          settings-path: ${{github.workspace}}
          cache: "maven"
      - name: Ejecucion de test
        run: mvn -B test --f pom.xml

  generation-build:
    needs: [execution-test]
    runs-on: ubuntu-22.04
    if: ${{github.event_name == 'push'}}
    steps:
      - name: Descargar ultimos cambios
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
      - name: Instalar y configurar JDK11
        uses: actions/setup-java@v3.4.1
        with:
          java-version: "11"
          distribution: "temurin"
          server-id: github
          settings-path: ${{github.workspace}}
          cache: "maven"
      - name: Generacion del artefacto
        
        run: mvn -B package -DskipTests -f pom.xml

  deploy-heroku:
    needs: [generation-build]
    runs-on: ubuntu-22.04
    if: ${{github.event_name == 'push'}}
    steps:
      - name: Deploy
        run: date